import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="darkMode">
      <body className={inter.className}>
        <div className="dark w-full relative flex justify-center items-center space-y-4">
          <Navbar />
        </div>

        {children}
      </body>
    </html>
  );
}
